# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160218135022 on 2016-04-08 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('all_night_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_night_1', to='farmacias.Pharmacy')),
                ('all_night_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_night_2', to='farmacias.Pharmacy')),
                ('close_at_24', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_at_24', to='farmacias.Pharmacy')),
            ],
        ),
    ]
