# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160218135022 on 2016-04-16 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='lat',
            field=models.DecimalField(decimal_places=16, default=-34.61752831970851, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='lng',
            field=models.DecimalField(decimal_places=16, default=-68.32381791970849, max_digits=18),
            preserve_default=False,
        ),
    ]
